### ISSUE TITLE
Redesign the items and catalogue items and systems landing pages 

### ISSUE THREAD

**Issue by joshuadkitenge** [ral-facilities/inventory-management-system#1016]
The items and catalogue items landing page should use the same template from common.

![image](https://github.com/user-attachments/assets/771f6830-f612-4832-9083-e56e56a8f1b9)

The redesign need to include tabs for attachments, gallery and information as the basic for catalogue item and items 

For systems the tabs should be for Items , Gallery and Attachments.
   

- [x] #1019
- [x] #1022
- [x] #1024
- [x] see if template can be made (extra)

**Comment by dajana212** [comment]
Hello, I would like to work on this issue, can you assign it to me?
