### ISSUE TITLE
Improve error message when a property migration fails due to a write conflict

### ISSUE THREAD

**Issue by joelvdavies** [ral-facilities/inventory-management-system#1121]
See https://github.com/ral-facilities/inventory-management-system-api/issues/412. Right now it will create a 500 error, leading to the broadcast `Something went wrong, please contact the system administrator`. Once the response is changed, the dialogue should display a message that gets the user to try again.

**Comment by joshuadkitenge** [comment]
The migration dialogs behave differently from the other dialogs. They close as soon as the request is sent, and the error handling is managed by the handleTransferState function instead of the handleIMS_APIError function. This means that if the backend parses the error message sensibly, it should show up in the error toast

**Comment by joelvdavies** [comment]
> The migration dialogs behave differently from the other dialogs. They close as soon as the request is sent, and the error handling is managed by the handleTransferState function instead of the handleIMS_APIError function. This means that if the backend parses the error message sensibly, it should show up in the error toast

Ah yes forgot about that, great, no changes needed here then. Thanks for the explanation.

**Comment by joelvdavies** [comment]
Now have
![image](https://github.com/user-attachments/assets/f39aea49-b380-46a9-ac12-433062eda8dd)
on https://github.com/ral-facilities/inventory-management-system-api/pull/433

**Comment by joelvdavies** [comment]
> The "Please try again" message should be included in the backend error message because users interacting solely with the backend wouldn't know how to proceed if they encountered this error.

Sure I was in two minds at the time so just picked one, is the rest of the message fine? So `Write conflict while adding property. Please try again later.`?
