### ISSUE TITLE
Combine dialogue open states in catalogue

### ISSUE THREAD

**Issue by joelvdavies** [ral-facilities/inventory-management-system#227]
I think we can combine the deleteCategoryDialogOpen, saveAs, edit react states and use a single one e.g. https://github.com/ral-facilities/inventory-management-system/blob/94d9ff67eb418659c64590155c7f8f4c4c054f07/src/systems/systems.component.tsx#L239-L242. (May also be able to use a single instance of the dialog as well https://github.com/ral-facilities/inventory-management-system/blob/94d9ff67eb418659c64590155c7f8f4c4c054f07/src/systems/systems.component.tsx#L392-L407)

**Comment by joshuadkitenge** [comment]
This is fine however it makes the code less readable.

**Comment by joshuadkitenge** [comment]
Yeah it something to think about after MVP has been delivered
