### ISSUE TITLE
HomePage 

### ISSUE THREAD

**Issue by joshuadkitenge** [ral-facilities/inventory-management-system#236]

**Comment by joelvdavies** [comment]
Not quite sure why but the positioning of the default one on SciGateway seems wrong (see Search/Download in image), may just be the React 18 branch but worth checking in case it will also effect the one we make (could be a display: flex or something)
![image](https://github.com/ral-facilities/inventory-management-system/assets/90245114/ebed2f80-7ccf-474f-88c6-8587e8653e10)

**Comment by joshuadkitenge** [comment]
That should not be a problem because we don't use scigateway default homepage, we create one in IMS based on the template

**Comment by joelvdavies** [comment]
Agreed, but it would still be good if they behaved the same, otherwise anything pulled across will be wrong as the App.css doesnt match.
