### ISSUE TITLE
Move and copy catalogue Items starts in directory above

### ISSUE THREAD

**Issue by joelvdavies** [ral-facilities/inventory-management-system#318]
I think it should really start in the same directory e.g. if copying to the current directory, navigation shouldn't be necessary. This is what systems & the obsolete dialogue does.

Other small things
- [ ] Clicking cancel resets the current selection
- [ ] Systems move dialog doesn't reset location when cancelled
- [ ] Can reduce catalogue category re-renders when opening and closing the move/copy dialogues by moving buttons into their own components & doing navigation in the dialogue itself
- [ ] Replace deprecated uses of `toBeCalledWith` -> `toHaveBeenCalledWith`, `toBeCalled` -> `toHaveBeenCalled`, `toBeCalledTimes` -> `toHaveBeenCalledTimes`

**Comment by joshuadkitenge** [comment]
@joelvdavies  This was done on purpose as a move to and copy for catalogue items' main purpose was to move catalogue items into different catalogue categories, not within itself. If the user wanted to do that, they should use the "save as" functionality. The directory above was chosen as that would be the most likely place that the catalogue category ( or catalogue category subtree) would exist.
