### ISSUE TITLE
Inconsistent table sizes on some move dialogues

### ISSUE THREAD

**Issue by joelvdavies** [ral-facilities/inventory-management-system#426]
e.g.
![image](https://github.com/ral-facilities/inventory-management-system/assets/90245114/7f3d3284-a10b-4a70-901c-7f539653da68)
vs
![image](https://github.com/ral-facilities/inventory-management-system/assets/90245114/2523846f-87e7-4b32-b9d0-a26ba646a630)

Check the others and obsolete dialogue as well.

**Comment by joshuadkitenge** [comment]
This is due to the error message @joelvdavies. This is so that an error message doesn't trigger the use of a vertical scroll bar in the dialog

**Comment by joshuadkitenge** [comment]
also the table size is different due the "add button" which is expected

**Comment by joelvdavies** [comment]
@joshuadkitenge But they both have error messages, and both have fixed sizes only they don't match anymore.
