### ISSUE TITLE
Replace description icon in tables with actual description but with tooltip?

### ISSUE THREAD

**Issue by joelvdavies** [ral-facilities/inventory-management-system#445]
Likely need datagateway-common's arrow tooltip for detecting the size.

**Comment by joshuadkitenge** [comment]
The simplest solution is to add a limit to the amount charterers in the description

**Comment by joelvdavies** [comment]
> The simplest solution is to add a limit to the amount charterers in the description
That would be a very short description, or potentially a lot of whitespace, the columns are resizable so it would would ultimately end up looking weird I think.

**Comment by joshuadkitenge** [comment]
For MVP it's fine

**Comment by joelvdavies** [comment]
Potentially use https://stackoverflow.com/questions/56588625/react-show-material-ui-tooltip-only-for-text-that-has-ellipsis
