### ISSUE TITLE
Creating multiple items at once  

### ISSUE THREAD

**Issue by joshuadkitenge** [ral-facilities/inventory-management-system#453]
Developer task:  

    Add quantity field in items dialog 

    Allow the user to generate a list for the serial numbers (append a number at the end e.g. PBO1 123)  

    Loop over the serial number and send multiple patch requests

**Comment by joelvdavies** [comment]
Just to add the example was a serial number with a `/1`  etc on the end. Also we discussed potentially having a field for this starting index to resolve the case of adding more when some already exist.
