### ISSUE TITLE
MSW memory leak 

### ISSUE THREAD

**Issue by joshuadkitenge** [ral-facilities/inventory-management-system#462]
![image](https://github.com/ral-facilities/inventory-management-system/assets/83226114/bee5fe67-cbb9-4a18-86bc-b35e2c9e6235)

**Comment by joshuadkitenge** [comment]
According to https://github.com/mswjs/msw/discussions/1650 it can be safely ignored

**Comment by joshuadkitenge** [comment]
I triggered this issue by switch tabs a of couple times

**Comment by joelvdavies** [comment]
Apparently it should have been fixed now anyway according to that tracked issue mentioned in the link.
