### ISSUE TITLE
Change the units field in the Catalogue category form to a dropdown (non-MVP)

### ISSUE THREAD

**Issue by joshuadkitenge** [ral-facilities/inventory-management-system#49]
- [ ] Implement an API request to get list of units.
- [ ] Change the text box into a dropdown (Select)

![image](https://github.com/ral-facilities/inventory-management-system/assets/83226114/d61b2366-9f6f-4d84-b226-cd4c046fb588)

**Comment by VKTB** [comment]
Superseded by https://github.com/ral-facilities/inventory-management-system/issues/266
