### ISSUE TITLE
Fix footer disappearing on scigateway when decreasing screen width

### ISSUE THREAD

**Issue by MatteoGuarnaccia5** [ral-facilities/inventory-management-system#558]
![Animation](https://github.com/ral-facilities/inventory-management-system/assets/144466888/f45d4803-399e-4124-b352-c25cdba9a5a8)

Footer disappears whenever you decrease the screen with past a certain point

**Comment by joelvdavies** [comment]
This appears to have been done on purpose in https://github.com/ral-facilities/scigateway/pull/1281. Not sure how the other links are supposed to be accessed in this case though.

**Comment by joshuadkitenge** [comment]
Look at comment above
