### ISSUE TITLE
preserving filter state of datetimes does not work

### ISSUE THREAD

**Issue by MatteoGuarnaccia5** [ral-facilities/inventory-management-system#597]
If you filter any of the tables (example below) by a datetime field, then send that URL link. It does not open the correct table state.
The filtered field has an error, after clearing the `Clear filters` button no longer works and stays active even after clearing all filters.

![Animation](https://github.com/ral-facilities/inventory-management-system/assets/144466888/d87e6824-6854-4d4c-9f64-e8d0837cb5ce)

**Comment by MatteoGuarnaccia5** [comment]
Also using the back arrow to navigate back to a table with a filtered state has the same effect

**Comment by joelvdavies** [comment]
Good spot!, yes this looks like a fun one to fix 😄,it looks like its an issue with the types.
