### ISSUE TITLE
System Items Table Loses Catalogue Item Name Grouping After Refresh

### ISSUE THREAD

**Issue by joshuadkitenge** [ral-facilities/inventory-management-system#610]
https://github.com/ral-facilities/inventory-management-system/assets/83226114/2180b495-1d2a-4fe5-99ee-f0c6df3a8271

**Comment by joelvdavies** [comment]
This is an issue only with the drag and drop group, normal grouping is fine, so likely just an MRT inconsistency again.

**Comment by joshuadkitenge** [comment]
Can the drag and drop be disabled ?

**Comment by joshuadkitenge** [comment]
https://www.material-react-table.com/docs/guides/column-grouping#hide-drag-buttons-for-grouping
